## numpy

In [2]:
import numpy as np

In [ ]:
lst = [1, 2, 3]
lst2 = [4, 5, 6]
arr = np.array(lst)
arr

array([1, 2, 3])

In [ ]:
arr2 = np.array(lst2)
arr2

array([4, 5, 6])

In [ ]:
arr3 = arr + arr2
arr3

array([5, 7, 9])

In [ ]:
lst3 = lst + lst2
lst3

[1, 2, 3, 4, 5, 6]

In [ ]:
arr4 = arr - arr2
arr4

array([-3, -3, -3])

In [ ]:
arr5 = arr * arr2
arr5

array([ 4, 10, 18])

In [ ]:
matrix = [[1, 2, 3], [4, 5, 6], [7, 8 , 9]]
amatrix = np.array(matrix)
print(matrix)
amatrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
lst6 = []
for i in range(1, 101):
  if i % 5 == 0:
    lst6.append(i)

lst6


[5,
 10,
 15,
 20,
 25,
 30,
 35,
 40,
 45,
 50,
 55,
 60,
 65,
 70,
 75,
 80,
 85,
 90,
 95,
 100]

In [ ]:
arr6 = np.arange(0, 100, 5)
arr6.shape


(20,)

In [ ]:
arr6.reshape(5, 4)

array([[ 0,  5, 10, 15],
       [20, 25, 30, 35],
       [40, 45, 50, 55],
       [60, 65, 70, 75],
       [80, 85, 90, 95]])

In [ ]:
arr7 = np.arange(1, 251)
arr7.reshape(25, 10)

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100],
       [101, 102, 103, 104, 105, 106, 107, 108, 109, 110],
       [111, 112, 113, 114, 115, 116, 117, 118, 119, 120],
       [121, 122, 123, 124, 125, 126, 127, 128, 129, 130],
       [131, 132, 133, 134, 135, 136, 137, 138, 139, 140],
       [141, 142, 143, 144, 145, 146, 147, 148, 149, 150],
       [151, 152, 153, 154, 155, 156, 157, 158, 159, 160],
       [161, 162, 163, 164, 165, 166, 167, 168, 169, 170

In [ ]:
arr8 = np.ones(250)
arr8.reshape(25, 10)

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 

In [4]:
x = np.array("salam")
x

array('salam', dtype='<U5')